### ISSUE TITLE
Consulardark Manipulation Error

### ISSUE THREAD

**Issue by SirFairlie** [rtotheichie/Avrae-Aliases#108]
**Describe the bug**
Attepmted to add the Manipulation subclass using the Verbose Character tool and when I use the !Level Consulardark Manipulation
it comes up with an error evaluating expression and says it's an issue with the user-created command it works for other subclasses though I have not tested them all  

**Severity**
Low

**Context**
The command doesn't work and Avrae says it's an error with the coding using the !Level Consulardark Manipulation

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the Verbose Character tool. 
2. Add the Gvar sw5e pack 
3. Use the tool to run the !Level Consulardark manipulation
4. See Error

**Expected behavior**
It should add the Manipulation Archetype/subclass to my character

**Screenshots**
![image](https://user-images.githubusercontent.com/100181416/155140497-02d9c43b-86c1-4101-8c31-475bf82ee100.png)

**Additional context**

**Comment by rtotheichie** [comment]
Thank you for the report! As Avrae v4 has released, most everything will require a significant rewrite.  In this case, the issue is with the `!level` alias, which is controlled by somebody else.  Once they have fixed it (if they have not already), I will try to make sure everything in the GVAR still works properly.
